replicaCount: 2

image:
  repository: ghcr.io/own4rd/credit-score-service
  tag: "latest"

namespace: credit-study

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

hpa:
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

ingress:
  host: credit-api.local
  path: /api/credit/score
