apiVersion: v1
kind: ConfigMap
metadata:
  name: credit-release-service-config
  namespace: {{ .Values.namespace }}
data:
  CREDIT_AMOUNT_TIER_20_30: {{ .Values.creditAmounts.tier2030 | quote }}
  CREDIT_AMOUNT_TIER_30_40: {{ .Values.creditAmounts.tier3040 | quote }}
  CREDIT_AMOUNT_TIER_40_PLUS: {{ .Values.creditAmounts.tier40Plus | quote }}
