apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-release-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: credit-release-service
  template:
    metadata:
      labels:
        app: credit-release-service
    spec:
      containers:
      - name: credit-release-service
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080
          name: http
        envFrom:
        - configMapRef:
            name: credit-release-service-config
        resources:
{{ toYaml .Values.resources | nindent 10 }}
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: http
        livenessProbe:
          httpGet:
            path: /q/health/live
            port: http
